spring:
  config:
    active:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to Public bank loans related Prod APIs "
  contactDetails:
    name: "Sandeep - Developer"
    email: "sandeep@publicbank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345